[tool.poetry]
name = "converter"
version = "0.1.0"
description = ""
authors = ["josephfierlinger <josephfierlinger@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
prompt = "^0.4.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
convert-distance = 'converter.scripts.convert-distance:main'
convert-currency-interactive = 'converter.scripts.convert-currency-interactive:main'
convert-currency = 'converter.scripts.convert-currency:main'
